[package]
name = "fizz_buzz"
version = "0.1.0"
authors = ["Casey Allred <sbditto@gmail.com>"]

[dependencies]
iron = "*"
router = "*"
mount = "*"
url = "*"

[dependencies.awesome]
name = "awesome"
path = "../awesome/"

[dependencies.staticfile]
git = "https://github.com/iron/staticfile.git"

